language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - android-28
    - platform-tools

branches:
  except:
    - gh-pages

# Disable Travis container-based infrastructure to correct
# resource consumption in gradle presumably due to dexing.
sudo: true
